"use client";

/**
 * Branded PDF builder for the DataIsData Command Center.
 * Every export (invoices, P&L, tracker reports, lists) goes through here so
 * they share the same header, colours, typography and footer.
 */
import type { jsPDF as JsPDFType } from "jspdf";

export const BRAND = {
  primary: [20, 70, 35] as [number, number, number], // #144623
  dark: [25, 59, 34] as [number, number, number], // #193b22
  bright: [5, 137, 62] as [number, number, number], // #05893e
  light: [225, 245, 228] as [number, number, number], // #e1f5e4
  ink: [17, 24, 39] as [number, number, number], // #111827
  muted: [107, 114, 128] as [number, number, number], // #6b7280
  line: [229, 231, 235] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
  amber: [217, 119, 6] as [number, number, number],
  silver: [226, 226, 222] as [number, number, number],
};

let logoCache: string | null = null;
async function loadLogo(): Promise<string | null> {
  if (logoCache) return logoCache;
  try {
    const res = await fetch("/brand/dataisdata-mark-silver.png");
    const blob = await res.blob();
    logoCache = await new Promise<string>((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve(r.result as string);
      r.onerror = reject;
      r.readAsDataURL(blob);
    });
    return logoCache;
  } catch {
    return null;
  }
}

export interface PdfMeta {
  title: string;
  subtitle?: string;
  preparedBy?: string;
  orientation?: "portrait" | "landscape";
  confidential?: boolean;
  /** Client-facing documents (invoices) use the public tagline and hide internal "generated by" details. */
  clientFacing?: boolean;
}

export interface Kpi {
  label: string;
  value: string;
  sub?: string;
  tone?: "default" | "good" | "bad" | "warn";
}

type Cell = string | number | { content: string; styles?: Record<string, unknown> };

export class BrandedPdf {
  doc: JsPDFType;
  y: number;
  readonly margin = 40;
  private meta: PdfMeta;
  private logo: string | null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private autoTable: any;

  private constructor(doc: JsPDFType, meta: PdfMeta, logo: string | null, autoTable: unknown) {
    this.doc = doc;
    this.meta = meta;
    this.logo = logo;
    this.autoTable = autoTable;
    this.y = 0;
    this.drawFirstHeader();
  }

  static async create(meta: PdfMeta): Promise<BrandedPdf> {
    const [{ jsPDF }, autoTableMod, logo] = await Promise.all([import("jspdf"), import("jspdf-autotable"), loadLogo()]);
    const doc = new jsPDF({ unit: "pt", format: "letter", orientation: meta.orientation || "portrait" });
    doc.setProperties({ title: `${meta.title} — DataIsData`, author: meta.preparedBy || "DataIsData", creator: "DataIsData Command Center" });
    return new BrandedPdf(doc, meta, logo, autoTableMod.default);
  }

  get width() {
    return this.doc.internal.pageSize.getWidth();
  }
  get height() {
    return this.doc.internal.pageSize.getHeight();
  }
  get contentWidth() {
    return this.width - this.margin * 2;
  }

  private drawFirstHeader() {
    const d = this.doc;
    const h = 92;
    d.setFillColor(...BRAND.dark);
    d.rect(0, 0, this.width, h, "F");
    d.setFillColor(...BRAND.primary);
    d.rect(this.width * 0.55, 0, this.width * 0.45, h, "F");
    d.setFillColor(...BRAND.bright);
    d.rect(0, h, this.width, 3, "F");
    if (this.logo) d.addImage(this.logo, "PNG", this.margin, 20, 52, 52);
    d.setTextColor(255, 255, 255);
    d.setFont("helvetica", "bold");
    d.setFontSize(20);
    d.text("DataIsData", this.margin + 64, 44);
    d.setFont("helvetica", "normal");
    d.setFontSize(8.5);
    d.setTextColor(...BRAND.silver);
    d.text(this.meta.clientFacing ? "INNOVATION AS A SERVICE" : "COMMAND CENTER", this.margin + 64, 59, { charSpace: 1.5 });

    d.setTextColor(255, 255, 255);
    d.setFont("helvetica", "bold");
    d.setFontSize(15);
    d.text(this.meta.title, this.width - this.margin, 42, { align: "right" });
    d.setFont("helvetica", "normal");
    d.setFontSize(9);
    d.setTextColor(...BRAND.silver);
    if (this.meta.subtitle) d.text(this.meta.subtitle, this.width - this.margin, 58, { align: "right" });
    if (!this.meta.clientFacing) {
      const gen = `Generated ${new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}${this.meta.preparedBy ? ` · ${this.meta.preparedBy}` : ""}`;
      d.text(gen, this.width - this.margin, 72, { align: "right" });
    }
    this.y = h + 28;
  }

  private drawContinuationHeader() {
    const d = this.doc;
    d.setFillColor(...BRAND.dark);
    d.rect(0, 0, this.width, 34, "F");
    d.setFillColor(...BRAND.bright);
    d.rect(0, 34, this.width, 2, "F");
    if (this.logo) d.addImage(this.logo, "PNG", this.margin, 7, 20, 20);
    d.setTextColor(255, 255, 255);
    d.setFont("helvetica", "bold");
    d.setFontSize(10);
    d.text("DataIsData", this.margin + 26, 21);
    d.setFont("helvetica", "normal");
    d.setTextColor(...BRAND.silver);
    d.text(this.meta.title, this.width - this.margin, 21, { align: "right" });
  }

  addPage() {
    this.doc.addPage();
    this.headerDrawn.add(this.doc.getCurrentPageInfo().pageNumber);
    this.drawContinuationHeader();
    this.y = 58;
  }

  ensureSpace(h: number) {
    if (this.y + h > this.height - 50) this.addPage();
  }

  heading(text: string, sub?: string) {
    if (this.y > 140) this.y += 8;
    this.ensureSpace(48);
    const d = this.doc;
    d.setFillColor(...BRAND.bright);
    d.rect(this.margin, this.y - 9, 3, 13, "F");
    d.setFont("helvetica", "bold");
    d.setFontSize(12.5);
    d.setTextColor(...BRAND.ink);
    d.text(text, this.margin + 10, this.y + 2);
    this.y += 10;
    if (sub) {
      d.setFont("helvetica", "normal");
      d.setFontSize(8.5);
      d.setTextColor(...BRAND.muted);
      const lines = d.splitTextToSize(sub, this.contentWidth - 10);
      d.text(lines, this.margin + 10, this.y + 6);
      this.y += lines.length * 11;
    }
    this.y += 10;
  }

  paragraph(text: string, opts: { size?: number; color?: [number, number, number]; bold?: boolean } = {}) {
    const d = this.doc;
    d.setFont("helvetica", opts.bold ? "bold" : "normal");
    d.setFontSize(opts.size || 9.5);
    d.setTextColor(...(opts.color || BRAND.ink));
    const lines = d.splitTextToSize(text, this.contentWidth);
    const lh = (opts.size || 9.5) * 1.35;
    this.ensureSpace(lines.length * lh + 4);
    d.text(lines, this.margin, this.y);
    this.y += lines.length * lh + 6;
  }

  kpis(items: Kpi[], perRow = 4) {
    const d = this.doc;
    const gap = 10;
    const w = (this.contentWidth - gap * (perRow - 1)) / perRow;
    const h = 58;
    for (let i = 0; i < items.length; i += perRow) {
      this.ensureSpace(h + gap);
      items.slice(i, i + perRow).forEach((k, j) => {
        const x = this.margin + j * (w + gap);
        d.setFillColor(248, 250, 249);
        d.setDrawColor(...BRAND.line);
        d.roundedRect(x, this.y, w, h, 6, 6, "FD");
        d.setFillColor(...(k.tone === "bad" ? BRAND.red : k.tone === "warn" ? BRAND.amber : k.tone === "good" ? BRAND.bright : BRAND.primary));
        d.rect(x, this.y + 8, 2.5, h - 16, "F");
        d.setFont("helvetica", "bold");
        d.setFontSize(6.8);
        d.setTextColor(...BRAND.muted);
        d.text(k.label.toUpperCase(), x + 10, this.y + 16, { charSpace: 0.4, maxWidth: w - 16 });
        d.setFontSize(13.5);
        d.setTextColor(...(k.tone === "bad" ? BRAND.red : BRAND.ink));
        d.text(k.value, x + 10, this.y + 35, { maxWidth: w - 16 });
        if (k.sub) {
          d.setFont("helvetica", "normal");
          d.setFontSize(7);
          d.setTextColor(...BRAND.muted);
          d.text(k.sub, x + 10, this.y + 48, { maxWidth: w - 16 });
        }
      });
      this.y += h + gap;
    }
    this.y += 6;
  }

  keyValue(rows: [string, string][], opts: { boldLast?: boolean } = {}) {
    const d = this.doc;
    rows.forEach(([k, v], i) => {
      this.ensureSpace(18);
      const last = opts.boldLast && i === rows.length - 1;
      d.setDrawColor(...BRAND.line);
      d.line(this.margin, this.y + 5, this.margin + this.contentWidth, this.y + 5);
      d.setFont("helvetica", last ? "bold" : "normal");
      d.setFontSize(9.5);
      d.setTextColor(...(last ? BRAND.ink : BRAND.muted));
      d.text(k, this.margin, this.y);
      d.setFont("helvetica", "bold");
      d.setTextColor(...BRAND.ink);
      d.text(v, this.margin + this.contentWidth, this.y, { align: "right" });
      this.y += 18;
    });
    this.y += 6;
  }

  table(opts: {
    head: string[];
    body: Cell[][];
    foot?: Cell[][];
    columnStyles?: Record<number, Record<string, unknown>>;
    fontSize?: number;
    alignRight?: number[];
  }) {
    const columnStyles: Record<number, Record<string, unknown>> = { ...(opts.columnStyles || {}) };
    (opts.alignRight || []).forEach((i) => (columnStyles[i] = { halign: "right", ...(columnStyles[i] || {}) }));
    this.ensureSpace(60);
    this.autoTable(this.doc, {
      startY: this.y,
      head: [opts.head],
      body: opts.body.length ? opts.body : [[{ content: "No records", colSpan: opts.head.length, styles: { halign: "center", textColor: BRAND.muted } }]],
      foot: opts.foot,
      margin: { top: 58, left: this.margin, right: this.margin, bottom: 48 },
      theme: "grid",
      styles: {
        font: "helvetica",
        fontSize: opts.fontSize || 8.5,
        cellPadding: 5,
        textColor: BRAND.ink,
        lineColor: BRAND.line,
        lineWidth: 0.5,
        overflow: "linebreak",
      },
      headStyles: { fillColor: BRAND.primary, textColor: [255, 255, 255], fontStyle: "bold", fontSize: (opts.fontSize || 8.5) - 0.5 },
      footStyles: { fillColor: BRAND.light, textColor: BRAND.ink, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [249, 252, 250] },
      columnStyles,
      didDrawPage: () => {
        // Continuation pages created by autotable need our branded header.
        const current = this.doc.getCurrentPageInfo().pageNumber;
        if (!this.headerDrawn.has(current)) {
          this.headerDrawn.add(current);
          this.drawContinuationHeader();
        }
      },
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    this.y = (this.doc as any).lastAutoTable.finalY + 18;
  }

  private headerDrawn = new Set<number>([1]);

  /** Grouped / stacked bar chart drawn with vector primitives. */
  barChart(opts: {
    labels: string[];
    series: { name: string; values: number[]; color: [number, number, number] }[];
    height?: number;
    format?: (n: number) => string;
    line?: { name: string; values: (number | null)[]; color: [number, number, number] };
  }) {
    const d = this.doc;
    const h = opts.height || 170;
    this.ensureSpace(h + 40);
    const x0 = this.margin + 48;
    const y0 = this.y;
    const w = this.contentWidth - 48;
    const all = [...opts.series.flatMap((s) => s.values), ...(opts.line ? (opts.line.values.filter((v) => v !== null) as number[]) : [])];
    const max = Math.max(1, ...all);
    const min = Math.min(0, ...all);
    const range = max - min || 1;
    const fmt = opts.format || ((n: number) => n.toFixed(0));
    const yOf = (v: number) => y0 + h - ((v - min) / range) * h;

    d.setFont("helvetica", "normal");
    d.setFontSize(7);
    for (let i = 0; i <= 4; i++) {
      const v = min + (range * i) / 4;
      const yy = yOf(v);
      d.setDrawColor(...BRAND.line);
      d.line(x0, yy, x0 + w, yy);
      d.setTextColor(...BRAND.muted);
      d.text(fmt(v), x0 - 6, yy + 2.5, { align: "right" });
    }
    const n = opts.labels.length || 1;
    const groupW = w / n;
    const barW = Math.max(2, (groupW * 0.7) / Math.max(1, opts.series.length));
    opts.labels.forEach((label, i) => {
      opts.series.forEach((s, j) => {
        const v = s.values[i] || 0;
        const x = x0 + i * groupW + groupW * 0.15 + j * barW;
        const top = yOf(Math.max(0, v));
        const bottom = yOf(Math.min(0, v));
        d.setFillColor(...s.color);
        d.rect(x, top, barW - 1, Math.max(0.5, bottom - top), "F");
      });
      d.setTextColor(...BRAND.muted);
      d.text(label, x0 + i * groupW + groupW / 2, y0 + h + 11, { align: "center" });
    });
    if (opts.line) {
      d.setDrawColor(...opts.line.color);
      d.setLineWidth(1.4);
      let prev: [number, number] | null = null;
      opts.line.values.forEach((v, i) => {
        if (v === null) {
          prev = null;
          return;
        }
        const pt: [number, number] = [x0 + i * groupW + groupW / 2, yOf(v)];
        if (prev) d.line(prev[0], prev[1], pt[0], pt[1]);
        d.setFillColor(...opts.line!.color);
        d.circle(pt[0], pt[1], 1.8, "F");
        prev = pt;
      });
      d.setLineWidth(0.5);
    }
    // legend
    let lx = x0;
    const ly = y0 + h + 26;
    [...opts.series.map((s) => ({ name: s.name, color: s.color })), ...(opts.line ? [{ name: opts.line.name, color: opts.line.color }] : [])].forEach((s) => {
      d.setFillColor(...s.color);
      d.rect(lx, ly - 6, 8, 8, "F");
      d.setTextColor(...BRAND.ink);
      d.text(s.name, lx + 12, ly + 1);
      lx += d.getTextWidth(s.name) + 30;
    });
    this.y = ly + 18;
  }

  insights(items: { severity: string; title: string; detail: string; category?: string }[]) {
    const d = this.doc;
    const colors: Record<string, [number, number, number]> = {
      critical: BRAND.red,
      warning: BRAND.amber,
      info: BRAND.primary,
      positive: BRAND.bright,
    };
    items.forEach((it) => {
      d.setFont("helvetica", "normal");
      d.setFontSize(8.5);
      const lines = d.splitTextToSize(it.detail, this.contentWidth - 22);
      const h = 18 + lines.length * 11 + 8;
      this.ensureSpace(h + 6);
      d.setFillColor(250, 251, 250);
      d.setDrawColor(...BRAND.line);
      d.roundedRect(this.margin, this.y, this.contentWidth, h, 5, 5, "FD");
      d.setFillColor(...(colors[it.severity] || BRAND.primary));
      d.rect(this.margin, this.y, 3.5, h, "F");
      d.setFont("helvetica", "bold");
      d.setFontSize(9.5);
      d.setTextColor(...BRAND.ink);
      d.text(it.title, this.margin + 12, this.y + 14, { maxWidth: this.contentWidth - 110 });
      if (it.category) {
        d.setFont("helvetica", "bold");
        d.setFontSize(6.8);
        d.setTextColor(...(colors[it.severity] || BRAND.primary));
        d.text(`${it.severity.toUpperCase()} · ${it.category.toUpperCase()}`, this.margin + this.contentWidth - 10, this.y + 14, { align: "right" });
      }
      d.setFont("helvetica", "normal");
      d.setFontSize(8.5);
      d.setTextColor(...BRAND.muted);
      d.text(lines, this.margin + 12, this.y + 28);
      this.y += h + 6;
    });
  }

  private drawFooters() {
    const total = this.doc.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      this.doc.setPage(i);
      const d = this.doc;
      d.setDrawColor(...BRAND.line);
      d.line(this.margin, this.height - 32, this.width - this.margin, this.height - 32);
      d.setFont("helvetica", "normal");
      d.setFontSize(7.5);
      d.setTextColor(...BRAND.muted);
      d.text(
        this.meta.clientFacing ? `DataIsData · ${this.meta.title}` : `${this.meta.confidential === false ? "" : "Confidential · "}DataIsData Command Center · ${this.meta.title}`,
        this.margin,
        this.height - 20
      );
      d.text(`Page ${i} of ${total}`, this.width - this.margin, this.height - 20, { align: "right" });
    }
  }

  save(filename: string) {
    this.drawFooters();
    const safe = filename.replace(/[^a-z0-9-_ .]/gi, "").replace(/\s+/g, "-");
    this.doc.save(safe.endsWith(".pdf") ? safe : `${safe}.pdf`);
  }

  /** For tests: returns the PDF as an ArrayBuffer instead of downloading. */
  output(): ArrayBuffer {
    this.drawFooters();
    return this.doc.output("arraybuffer");
  }
}

export function pdfDateStamp() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
